### ISSUE TITLE
Not working with K2 verson 3

### ISSUE THREAD

**Issue by OlleZettergren** [getk2/k2-links-for-jce#1]
It's not working with K2 version 3 depending on database changes in K2 3.

**Comment by OlleZettergren** [comment]
Any progress on this problem?

**Comment by kavadas** [comment]
Just updated the code to work with K2v3. Can you please grab a fresh copy and verify that it works for you also?

**Comment by OlleZettergren** [comment]
Hi!

Works like a charm :)
Thanx!

/ Olle - Actionwave

2015-01-14 14:11 GMT+01:00 Lefteris Kavadas notifications@github.com:

> Just updated the code to work with K2v3. Can you please grab a fresh copy
> and verify that it works for you also?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joomlaworks/K2-Links-for-JCE/issues/1#issuecomment-69913607
> .

## 

---

_Olle Zettergren_
Webdeveloper
Actionwave Development AB
0703-298081 - olle@actionwave.se - www.actionwave.se
