### ISSUE TITLE
k2 links in jce adding alias instead of item id in url

### ISSUE THREAD

**Issue by ash13876** [getk2/k2-links-for-jce#15]
k2 link is adding item alias instead of id which breaks the page in frontend
![screenshot 2](https://user-images.githubusercontent.com/10802887/39686379-b615f616-5196-11e8-9304-837d09ab0962.png)

**Comment by fevangelou** [comment]
As you can see, the ID is right in front of the item alias. How exactly does it break your site?

**Comment by ash13876** [comment]
page breaks if there is an alias in front
http://trendcouncil.com/web/index.php?option=com_k2&view=item&id=3607

but when you visit the page directly it works fine
http://trendcouncil.com/web/index.php?option=com_k2&view=item&id=3607:the-line-by-k-ss18&Itemid=696
