### ISSUE TITLE
Categories not expanding

### ISSUE THREAD

**Issue by ghost** [getk2/k2-links-for-jce#2]
Folks,

I've been using this extension for quite a long time.  Nice job.  I'm running into a problem when I attempt to navigate down a K2 category hierarchy.  It appears to just stop opening categories after about 3 levels.  Can you see if this is a bug?  Thanks - Joe

**Comment by genesisfan** [comment]
I've the same issue.

**Comment by kavadas** [comment]
I cannot verify the issue. Just tested and i was able to go more than three levels in.

**Comment by genesisfan** [comment]
After the third level no items are displayed?
![k2-links-for-jce_example](https://cloud.githubusercontent.com/assets/1644862/5903064/cb538bb8-a57f-11e4-947c-00935c90e042.png)

While there are items active:
![k2-links-for-jce_example2](https://cloud.githubusercontent.com/assets/1644862/5903099/fe3086da-a57f-11e4-9060-d4668a9ee0aa.png)

**Comment by kavadas** [comment]
@genesisfan What's the version of K2 that you are using? Ensure that Joomla!/K2/JCE are all updated their latest versions.

**Comment by genesisfan** [comment]
I'm using the latest version Jooma! 3.3.6/K2 2.6.9/JCE 2.4.6 and K2 Links for JCE 2.0.1.

**Comment by kavadas** [comment]
Are those categories published? Do you have the appropriate access level to view them?

**Comment by genesisfan** [comment]
Yes, the categories are published and I do have the appropriate access level.

**Comment by WallEnd** [comment]
And so? Somebody knows, how to fix this bug?

**Comment by kavadas** [comment]
@WallEnd Have you checked the categories publish state and access level? As i wrote in a previous answer, it is working fine for me, i cannot verify the issue.

**Comment by WallEnd** [comment]
All of them are published and have a Public access level. But my promblem in more than five levels in.

**Comment by kavadas** [comment]
@WallEnd 
Are you using the version from this repository or you are using an other version. I recommend to download the repository version from https://github.com/joomlaworks/K2-Links-for-JCE/archive/master.zip and let me know.

**Comment by WallEnd** [comment]
@kavadas 
Yes, i'm using extension from this repo. 
![trouble](https://cloud.githubusercontent.com/assets/12442336/7647349/0eb16374-faf5-11e4-9641-ad3337cca8f7.png)
It is strangely, but as you can see at screen, previous category opened and articles are visible, but we have bug when we try to open next category.  And both of them are identical.

**Comment by kavadas** [comment]
Since this occurs on a specific category open the browser developer tools to inspect the request that is made when you click on that category.

**Comment by WallEnd** [comment]
Request:
/administrator/index.php?option=com_jce&view=editor&layout=plugin&plugin=link&component_id=16
Form Data:
json:{"fn":"getLinks","args":{"option":"com_k2","view":"itemlist","task":"category","id":"38:4-etap-pharaons-cross-country-rally","Itemid":"149"}}
format:raw
searchphrase:all
ordering:newest
popup_list:

## wf57f594e971d449c7385a3af5630fa47b:1

Response:
folders: []

**Comment by genesisfan** [comment]
Any progress here?

**Comment by williamconifer** [comment]
I am having the exact same problem. Joomla 3.4.7, K2 2.6.9, JCE 2.5.12, k2 Links for JCE 2.0.1 from Git Repo. 

I an getting no js errors when clicking on the unresponsive folder in folder tree view. the K2 item is published and is public. I CAN find/create the link if I use the k2 Links for JCE search. 

This is a REALLY big problem for me since my client is a city government using this plugin to link to meeting agenda item attachments. 

I need help!

**Comment by kavadas** [comment]
@williamconifer 

Please do not create duplicate posts. I have already answered to the issue you created.

@genesisfan @WallEnd 

I still cannot verify the issue. Just tested with the latest versions and everything works fine for me. Get the K2 2.7.0 development version as well as the development version of the plugin from that repository and everything should work fine. If not check your browser console for any errors.

**Comment by williamconifer** [comment]
I have figured out what is causing the issue of the K2 category NOT showing the K2 items within. 

The issue happens if the K2 category name starts with a number! Note that I tested this using the K2 2.7 dev repo and K2 links for JCE repo version.

Example:
Issue appears with a Category title of "2015 PW Agenda Items"

Issue does NOT appear (works properly) when category title is:
"PW Agenda Items" or "PW Agenda Items 2015"

Kavadas, can we get this fixed?

**Comment by kavadas** [comment]
@williamconifer 

Can you provide more details on this? Just tested with a category named "2015 PW Agenda Items" and it  worked fine for me again.

**Comment by williamconifer** [comment]
Thanks for the fix. I can confirm that this fixes the issue on my end. Thanks again.

**Comment by kavadas** [comment]
@williamconifer 

Thank you for your feedback.
