### ISSUE TITLE
Error at "Search"

### ISSUE THREAD

**Issue by ghost** [getk2/k2-links-for-jce#3]
Searching Links got at Front- and Backend:

Uncaught exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND published=1' at line 1 SQL=SELECT id FROM ####_k2_tags WHERE LOWER(name) LIKE AND published=1 

Joomla-3.3.6, K2-2.6.9, JCE-2.4.5

**Comment by kavadas** [comment]
I don't think that this error is coming from our plugin. Enable Joomla! debugger to see which file is executing this query.

**Comment by ghost** [comment]
have tried to find out by Joomla debugger, can' find file. So it's not from PlugIn, i will set Search-Option on "No".

**Comment by kavadas** [comment]
You can try to uninstall the plugin and verify what i wrote. For me searching in the editor is working fine. Let me know if there are any news on this.

**Comment by ghost** [comment]
Tested on other Page works fine, so somethings wrong at 1st Page. But i don't know how to find "which file is executing this query". Have enabled Debugger but cant understand or don't know where to look. Thanks for your Helping.

**Comment by kavadas** [comment]
Can you provide detailed instructions regarding how i can reproduce the issue? I don't get what you mean you test it on other page? The page should be always the K2 item edit form, right?

**Comment by ghost** [comment]
You're right. I meant different Homepages i'm admin. One with in Error K2 item edit form, another without Error in K2 item edit form.
