### ISSUE TITLE
Search string in JCE does not see the K2 content.

### ISSUE THREAD

**Issue by lifelover2b** [getk2/k2-links-for-jce#6]
Perhaps not a bug, take it as a request for extension functionality. In JCE Links you can only select a K2 material from the list, but the search only sees the content Joomla. Search for K2 content is very useful, especially when there are over 300 materials in each category...
![2016-02-29 14-57-41](https://cloud.githubusercontent.com/assets/17545807/13393934/9c02d534-def5-11e5-9852-c78c018fe413.png)
![2016-02-29 14-58-27](https://cloud.githubusercontent.com/assets/17545807/13393938/a1d30cb8-def5-11e5-99f9-f5749f49860b.png)

**Comment by KlintMX** [comment]
Have the same issue

**Comment by ryandemmer** [comment]
The Search field uses the **Joomla** K2 Search plugin, the same one used to search the site in the front-end.

This must be enabled in JCE Editor Profiles -> Plugin Parameters -> Link, in the Search section (scroll to the bottom of the page)
