### ISSUE TITLE
can't get it installed: Warning  JInstaller: :Install: Can't find Joomla XML setup file.

### ISSUE THREAD

**Issue by frankazoid** [getk2/k2-links-for-jce#8]
am i missing anything?
joomla 3.5.1 K2 2.7.0

**Comment by ttouf** [comment]
same problem

**Comment by ghost** [comment]
same problem with me too. Is there anybody out there to help?

**Comment by ryandemmer** [comment]
Have you read the instructions?

> DOWNLOAD
> 
> You can grab the latest release here: https://github.com/getk2/k2-links-for-jce/archive/master.zip (v2.6.0)
> 
> Install using the Joomla Installer!
> 
> OLDER VERSIONS
> 
> Version 2.0.1 for JCE 2.5.x is available here - https://github.com/getk2/k2-links-for-jce/archive/2.0.x.zip
> 
> Install using the JCE Installer!

https://github.com/getk2/k2-links-for-jce

**Comment by wirecreative** [comment]
I had the previous version of this installed, which broke after the JCE upgrade.

I'm trying to install the updated plugin, but I'm getting a slightly different error upon uploading the installation file:

`Warning

JInstaller: :Install: File does not exist /home/xxxxxxx/public_html/tmp/install_583ba014bf30e/k2-links-for-jce-master/links-k2.php
Plugin Install: Could not copy files from the source.
×Error
Error installing plugin`

Joomla! 3.6.4, JCE Pro 2.6.0

**Comment by nvsdesign** [comment]
I get the same error as wirecreative.
How to solve this?

Joomla! 3.6.4, JCE Pro 2.6.0

**Comment by ryandemmer** [comment]
The installation has been fixed.

Download and install using the Joomla Extension Manager.

**Comment by wirecreative** [comment]
Thanks. After installing, I had to manually delete the old version's files from the components/com_jce/extensions/links  folder to get this new one to work. Now it seems to be fine.
